/**
 * Apple Calendar OAuth Service
 *
 * Handles authentication for Apple Calendar via iCloud CalDAV.
 *
 * Note: Apple iCloud uses a special OAuth flow that requires:
 * 1. Sign in with Apple for initial auth
 * 2. App-specific passwords for CalDAV access
 *
 * For enterprise apps, Apple recommends using Sign in with Apple
 * combined with app-specific passwords generated by the user.
 *
 * This implementation uses the Sign in with Apple OAuth flow to verify
 * the user's identity, then guides them to create an app-specific password
 * for CalDAV access.
 */

import { CalendarProvider } from '@prisma/client'
import type { CalendarOAuthService, CalendarOAuthTokens } from '../types'

// ============================================
// CONFIGURATION
// ============================================

const APPLE_CONFIG = {
  // Sign in with Apple endpoints
  authorizationEndpoint: 'https://appleid.apple.com/auth/authorize',
  tokenEndpoint: 'https://appleid.apple.com/auth/token',
  scopes: ['name', 'email'],
  // CalDAV endpoint for iCloud
  caldavEndpoint: 'https://caldav.icloud.com',
}

// ============================================
// SERVICE IMPLEMENTATION
// ============================================

export class AppleCalendarOAuthService implements CalendarOAuthService {
  readonly provider = CalendarProvider.APPLE

  private clientId: string
  private teamId: string
  private keyId: string
  private privateKey: string
  private redirectUri: string

  constructor() {
    this.clientId = process.env.APPLE_CALENDAR_CLIENT_ID || '' // Services ID
    this.teamId = process.env.APPLE_TEAM_ID || ''
    this.keyId = process.env.APPLE_KEY_ID || ''
    this.privateKey = process.env.APPLE_PRIVATE_KEY || ''
    this.redirectUri =
      process.env.APPLE_CALENDAR_REDIRECT_URI ||
      `${process.env.NEXT_PUBLIC_APP_URL}/api/integrations/calendar/callback/apple`

    if (!this.clientId) {
      console.warn(
        '[AppleCalendar] Missing APPLE_CALENDAR_CLIENT_ID (Services ID)'
      )
    }
  }

  /**
   * Generate client secret JWT for Apple OAuth
   *
   * Apple requires a signed JWT as the client_secret
   */
  private async generateClientSecret(): Promise<string> {
    // Apple requires ES256-signed JWT as client_secret
    // This is a simplified placeholder - in production, use a proper JWT library
    const header = {
      alg: 'ES256',
      kid: this.keyId,
    }

    const now = Math.floor(Date.now() / 1000)
    const payload = {
      iss: this.teamId,
      iat: now,
      exp: now + 86400 * 180, // 180 days max
      aud: 'https://appleid.apple.com',
      sub: this.clientId,
    }

    // In production, use jose or similar library to sign the JWT
    // For now, we'll throw an error if the key isn't configured
    if (!this.privateKey || !this.keyId || !this.teamId) {
      throw new Error('Apple OAuth not configured. Missing private key, key ID, or team ID.')
    }

    // This is a placeholder - actual implementation would use crypto
    // to sign the JWT with the ES256 algorithm
    const headerB64 = Buffer.from(JSON.stringify(header)).toString('base64url')
    const payloadB64 = Buffer.from(JSON.stringify(payload)).toString('base64url')

    // TODO: Implement proper ES256 signing with the private key
    // For now, return a placeholder that will fail if used
    console.warn('[AppleCalendar] JWT signing not fully implemented - use jose library')
    return `${headerB64}.${payloadB64}.signature_placeholder`
  }

  /**
   * Generate OAuth authorization URL
   */
  getAuthorizationUrl(state: string): string {
    const params = new URLSearchParams({
      client_id: this.clientId,
      redirect_uri: this.redirectUri,
      response_type: 'code',
      scope: APPLE_CONFIG.scopes.join(' '),
      response_mode: 'form_post', // Apple requires form_post
      state,
    })

    return `${APPLE_CONFIG.authorizationEndpoint}?${params.toString()}`
  }

  /**
   * Exchange authorization code for tokens
   *
   * Note: Apple tokens are for identity verification.
   * For CalDAV access, users need to generate an app-specific password.
   */
  async exchangeCodeForTokens(code: string): Promise<CalendarOAuthTokens> {
    const clientSecret = await this.generateClientSecret()

    const params = new URLSearchParams({
      code,
      client_id: this.clientId,
      client_secret: clientSecret,
      redirect_uri: this.redirectUri,
      grant_type: 'authorization_code',
    })

    const response = await fetch(APPLE_CONFIG.tokenEndpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: params.toString(),
    })

    if (!response.ok) {
      const error = await response.json()
      throw new Error(
        `Apple token exchange failed: ${error.error_description || error.error}`
      )
    }

    const data = await response.json()

    // Apple's id_token contains user info
    // We'll need the user to provide an app-specific password separately

    return {
      accessToken: data.access_token,
      refreshToken: data.refresh_token,
      expiresAt: new Date(Date.now() + (data.expires_in || 3600) * 1000),
      tokenType: data.token_type || 'Bearer',
    }
  }

  /**
   * Refresh an expired access token
   */
  async refreshAccessToken(refreshToken: string): Promise<CalendarOAuthTokens> {
    const clientSecret = await this.generateClientSecret()

    const params = new URLSearchParams({
      refresh_token: refreshToken,
      client_id: this.clientId,
      client_secret: clientSecret,
      grant_type: 'refresh_token',
    })

    const response = await fetch(APPLE_CONFIG.tokenEndpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: params.toString(),
    })

    if (!response.ok) {
      const error = await response.json()
      throw new Error(
        `Apple token refresh failed: ${error.error_description || error.error}`
      )
    }

    const data = await response.json()

    return {
      accessToken: data.access_token,
      refreshToken: data.refresh_token || refreshToken,
      expiresAt: new Date(Date.now() + (data.expires_in || 3600) * 1000),
      tokenType: data.token_type || 'Bearer',
    }
  }

  /**
   * Verify CalDAV credentials (app-specific password)
   *
   * Used after OAuth to verify the user's app-specific password works
   */
  async verifyCalDAVCredentials(
    email: string,
    appSpecificPassword: string
  ): Promise<boolean> {
    try {
      // Try a simple PROPFIND request to verify credentials
      const credentials = Buffer.from(`${email}:${appSpecificPassword}`).toString('base64')

      const response = await fetch(`${APPLE_CONFIG.caldavEndpoint}/`, {
        method: 'PROPFIND',
        headers: {
          Authorization: `Basic ${credentials}`,
          Depth: '0',
          'Content-Type': 'application/xml',
        },
        body: `<?xml version="1.0" encoding="utf-8" ?>
<D:propfind xmlns:D="DAV:">
  <D:prop>
    <D:current-user-principal/>
  </D:prop>
</D:propfind>`,
      })

      return response.ok || response.status === 207 // 207 Multi-Status is success for PROPFIND
    } catch (error) {
      console.error('[AppleCalendar] CalDAV verification failed:', error)
      return false
    }
  }
}

// Singleton instance
export const appleCalendarOAuth = new AppleCalendarOAuthService()
