"""initial schema

Revision ID: 481f5e08a28c
Revises:
Create Date: 2026-03-02 13:41:33.542147

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "481f5e08a28c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("risk_tier", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("event_data", sa.JSON(), nullable=False),
        sa.Column("source_service", sa.String(length=100), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("s3_archive_path", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_occurred_at"), "audit_events", ["occurred_at"], unique=False
    )
    op.create_index(op.f("ix_audit_events_org_id"), "audit_events", ["org_id"], unique=False)
    op.create_index(op.f("ix_audit_events_risk_tier"), "audit_events", ["risk_tier"], unique=False)
    op.create_table(
        "audit_sinks",
        sa.Column("sink_type", sa.String(length=50), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "compliance_frameworks",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("default_retention", sa.JSON(), nullable=False),
        sa.Column("required_audit_events", sa.JSON(), nullable=False),
        sa.Column("data_handling_rules", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "models",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("model_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("is_global", sa.Boolean(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_models_name"), "models", ["name"], unique=False)
    op.create_index(op.f("ix_models_org_id"), "models", ["org_id"], unique=False)
    op.create_table(
        "org_profiles",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("compliance_frameworks", sa.JSON(), nullable=False),
        sa.Column("retention_policies", sa.JSON(), nullable=False),
        sa.Column("privacy_settings", sa.JSON(), nullable=False),
        sa.Column("epsilon_budget", sa.Float(), nullable=False),
        sa.Column("epsilon_consumed", sa.Float(), nullable=False),
        sa.Column("budget_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("model_training_enabled", sa.Boolean(), nullable=False),
        sa.Column("audit_routing_config", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_org_profiles_org_id"), "org_profiles", ["org_id"], unique=True)
    op.create_table(
        "audit_routes",
        sa.Column("org_id", sa.UUID(), nullable=True),
        sa.Column("event_type_pattern", sa.String(length=200), nullable=False),
        sa.Column("risk_tier_min", sa.String(length=20), nullable=False),
        sa.Column("sink_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["sink_id"], ["audit_sinks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_routes_org_id"), "audit_routes", ["org_id"], unique=False)
    op.create_table(
        "model_versions",
        sa.Column("model_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("artifact_s3_path", sa.String(length=500), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("parent_version_id", sa.UUID(), nullable=True),
        sa.Column("deployed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["model_id"], ["models.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parent_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "org_compliance_overrides",
        sa.Column("org_profile_id", sa.UUID(), nullable=False),
        sa.Column("framework_name", sa.String(length=50), nullable=False),
        sa.Column("overrides", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_profile_id"], ["org_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "privacy_ledger",
        sa.Column("org_profile_id", sa.UUID(), nullable=False),
        sa.Column("epsilon_consumed", sa.Float(), nullable=False),
        sa.Column("operation_type", sa.String(length=100), nullable=False),
        sa.Column("model_id", sa.UUID(), nullable=True),
        sa.Column("model_version_id", sa.UUID(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["org_profile_id"], ["org_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_privacy_ledger_org_profile_id"), "privacy_ledger", ["org_profile_id"], unique=False
    )
    op.create_table(
        "model_deployments",
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("environment", sa.String(length=50), nullable=False),
        sa.Column("deployment_status", sa.String(length=50), nullable=False),
        sa.Column("traffic_percentage", sa.Float(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["version_id"], ["model_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model_deployments")
    op.drop_index(op.f("ix_privacy_ledger_org_profile_id"), table_name="privacy_ledger")
    op.drop_table("privacy_ledger")
    op.drop_table("org_compliance_overrides")
    op.drop_table("model_versions")
    op.drop_index(op.f("ix_audit_routes_org_id"), table_name="audit_routes")
    op.drop_table("audit_routes")
    op.drop_index(op.f("ix_org_profiles_org_id"), table_name="org_profiles")
    op.drop_table("org_profiles")
    op.drop_index(op.f("ix_models_org_id"), table_name="models")
    op.drop_index(op.f("ix_models_name"), table_name="models")
    op.drop_table("models")
    op.drop_table("compliance_frameworks")
    op.drop_table("audit_sinks")
    op.drop_index(op.f("ix_audit_events_risk_tier"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_org_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
