/**
 * Report Excel Generator
 *
 * Generates Excel reports with multiple worksheets for metrics and data.
 */

import ExcelJS from "exceljs";
import { ReportType } from "@prisma/client";
import { ReportMetricResult, ReportNarrativeSection } from "../types";

export interface ExcelReportData {
  organizationName: string;
  reportName: string;
  reportType: ReportType;
  reportingPeriod: {
    start: Date;
    end: Date;
  };
  generatedAt: Date;
  generatedBy: string;
  metrics: ReportMetricResult[];
  narratives: ReportNarrativeSection[];
  rawData?: Array<Record<string, unknown>>;
}

export interface ExcelGenerationOptions {
  includeRawData?: boolean;
  includeCharts?: boolean;
  colorScheme?: "default" | "professional" | "minimal";
}

/**
 * Generate an Excel report
 */
export async function generateReportExcel(
  data: ExcelReportData,
  options: ExcelGenerationOptions = {}
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();

  workbook.creator = "Scrybe";
  workbook.created = new Date();
  workbook.modified = new Date();
  workbook.title = data.reportName;

  // Add Summary worksheet
  addSummarySheet(workbook, data);

  // Add Metrics worksheet
  addMetricsSheet(workbook, data, options);

  // Add Narratives worksheet
  if (data.narratives.length > 0) {
    addNarrativesSheet(workbook, data);
  }

  // Add Raw Data worksheet if requested
  if (options.includeRawData && data.rawData && data.rawData.length > 0) {
    addRawDataSheet(workbook, data.rawData);
  }

  // Generate buffer
  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

/**
 * Add the summary worksheet
 */
function addSummarySheet(
  workbook: ExcelJS.Workbook,
  data: ExcelReportData
): void {
  const sheet = workbook.addWorksheet("Summary", {
    properties: { tabColor: { argb: "FF4A90D9" } },
  });

  // Set column widths
  sheet.columns = [
    { width: 25 },
    { width: 50 },
  ];

  // Title
  sheet.mergeCells("A1:B1");
  const titleCell = sheet.getCell("A1");
  titleCell.value = data.reportName;
  titleCell.font = { size: 18, bold: true };
  titleCell.alignment = { horizontal: "center" };

  // Subtitle
  sheet.mergeCells("A2:B2");
  const subtitleCell = sheet.getCell("A2");
  subtitleCell.value = getReportTypeLabel(data.reportType);
  subtitleCell.font = { size: 12, color: { argb: "FF666666" } };
  subtitleCell.alignment = { horizontal: "center" };

  // Empty row
  sheet.addRow([]);

  // Report details
  const details = [
    ["Organization", data.organizationName],
    [
      "Reporting Period",
      `${formatDate(data.reportingPeriod.start)} - ${formatDate(data.reportingPeriod.end)}`,
    ],
    ["Generated", formatDate(data.generatedAt)],
    ["Generated By", data.generatedBy],
  ];

  for (const [label, value] of details) {
    const row = sheet.addRow([label, value]);
    row.getCell(1).font = { bold: true };
  }

  // Empty rows
  sheet.addRow([]);
  sheet.addRow([]);

  // Key Metrics Summary
  sheet.addRow(["Key Metrics Summary"]).font = { size: 14, bold: true };
  sheet.addRow([]);

  // Add top metrics (first 5)
  const topMetrics = data.metrics.slice(0, 5);
  for (const metric of topMetrics) {
    const row = sheet.addRow([metric.name, metric.formattedValue]);
    row.getCell(1).font = { bold: true };
    row.getCell(2).alignment = { horizontal: "right" };

    if (metric.benchmarkStatus) {
      row.getCell(2).font = {
        color: { argb: getBenchmarkColor(metric.benchmarkStatus) },
      };
    }
  }
}

/**
 * Add the metrics worksheet
 */
function addMetricsSheet(
  workbook: ExcelJS.Workbook,
  data: ExcelReportData,
  options: ExcelGenerationOptions
): void {
  const sheet = workbook.addWorksheet("Metrics", {
    properties: { tabColor: { argb: "FF28A745" } },
  });

  // Set column widths
  sheet.columns = [
    { header: "Metric", key: "name", width: 40 },
    { header: "Value", key: "formattedValue", width: 20 },
    { header: "Category", key: "category", width: 20 },
    { header: "Status", key: "benchmarkStatus", width: 15 },
    { header: "Change", key: "changePercentage", width: 15 },
  ];

  // Style header row
  const headerRow = sheet.getRow(1);
  headerRow.font = { bold: true, color: { argb: "FFFFFFFF" } };
  headerRow.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FF4A5568" },
  };
  headerRow.alignment = { horizontal: "center" };

  // Add data rows
  for (const metric of data.metrics) {
    const row = sheet.addRow({
      name: metric.name,
      formattedValue: metric.formattedValue,
      category: formatCategory(metric.category),
      benchmarkStatus: metric.benchmarkStatus
        ? formatBenchmarkStatus(metric.benchmarkStatus)
        : "-",
      changePercentage: metric.changePercentage
        ? `${metric.changePercentage > 0 ? "+" : ""}${metric.changePercentage.toFixed(1)}%`
        : "-",
    });

    // Style benchmark status cell
    if (metric.benchmarkStatus) {
      row.getCell("benchmarkStatus").font = {
        color: { argb: getBenchmarkColor(metric.benchmarkStatus) },
      };
    }

    // Style change percentage cell
    if (metric.changePercentage) {
      row.getCell("changePercentage").font = {
        color: {
          argb: metric.changePercentage >= 0 ? "FF28A745" : "FFDC3545",
        },
      };
    }
  }

  // Auto-filter
  sheet.autoFilter = {
    from: "A1",
    to: `E${data.metrics.length + 1}`,
  };

  // Freeze header row
  sheet.views = [{ state: "frozen", ySplit: 1 }];
}

/**
 * Add the narratives worksheet
 */
function addNarrativesSheet(
  workbook: ExcelJS.Workbook,
  data: ExcelReportData
): void {
  const sheet = workbook.addWorksheet("Narratives", {
    properties: { tabColor: { argb: "FF6C757D" } },
  });

  // Set column widths
  sheet.columns = [
    { width: 25 },
    { width: 100 },
  ];

  let currentRow = 1;

  for (const narrative of data.narratives) {
    // Section title
    const titleCell = sheet.getCell(`A${currentRow}`);
    titleCell.value = narrative.title;
    titleCell.font = { size: 14, bold: true };
    currentRow++;

    // Section content - wrap text
    const contentCell = sheet.getCell(`A${currentRow}`);
    sheet.mergeCells(`A${currentRow}:B${currentRow}`);
    contentCell.value = narrative.content;
    contentCell.alignment = { wrapText: true, vertical: "top" };

    // Calculate row height based on content length
    const estimatedLines = Math.ceil(narrative.content.length / 100);
    sheet.getRow(currentRow).height = Math.max(15, estimatedLines * 15);

    currentRow += 2; // Add spacing between sections
  }
}

/**
 * Add raw data worksheet
 */
function addRawDataSheet(
  workbook: ExcelJS.Workbook,
  rawData: Array<Record<string, unknown>>
): void {
  const sheet = workbook.addWorksheet("Raw Data", {
    properties: { tabColor: { argb: "FFFFC107" } },
  });

  if (rawData.length === 0) return;

  // Get all unique keys from the data
  const allKeys = new Set<string>();
  for (const row of rawData) {
    Object.keys(row).forEach((key) => allKeys.add(key));
  }
  const headers = Array.from(allKeys);

  // Add header row
  sheet.addRow(headers);
  const headerRow = sheet.getRow(1);
  headerRow.font = { bold: true, color: { argb: "FFFFFFFF" } };
  headerRow.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FF4A5568" },
  };

  // Add data rows
  for (const row of rawData) {
    const values = headers.map((header) => {
      const value = row[header];
      if (value === null || value === undefined) return "";
      if (value instanceof Date) return formatDate(value);
      if (typeof value === "object") return JSON.stringify(value);
      return value;
    });
    sheet.addRow(values);
  }

  // Auto-filter
  sheet.autoFilter = {
    from: "A1",
    to: `${String.fromCharCode(65 + headers.length - 1)}${rawData.length + 1}`,
  };

  // Set column widths
  sheet.columns = headers.map(() => ({ width: 20 }));

  // Freeze header row
  sheet.views = [{ state: "frozen", ySplit: 1 }];
}

// ============================================
// HELPER FUNCTIONS
// ============================================

function getReportTypeLabel(reportType: ReportType): string {
  const labels: Record<ReportType, string> = {
    HUD_APR: "HUD Annual Performance Report",
    DOL_WORKFORCE: "DOL Workforce Performance Report",
    CALI_GRANTS: "California Grant Report",
    BOARD_REPORT: "Board Report",
    IMPACT_REPORT: "Impact Report",
    CUSTOM: "Custom Report",
  };
  return labels[reportType];
}

function formatDate(date: Date): string {
  return new Intl.DateTimeFormat("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  }).format(date);
}

function formatCategory(category: string): string {
  return category
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function formatBenchmarkStatus(status: "below" | "good" | "excellent"): string {
  const labels: Record<string, string> = {
    below: "Below Target",
    good: "Good",
    excellent: "Excellent",
  };
  return labels[status] || status;
}

function getBenchmarkColor(
  status: "below" | "good" | "excellent"
): string {
  const colors: Record<string, string> = {
    below: "FFDC3545", // Red
    good: "FF007BFF", // Blue
    excellent: "FF28A745", // Green
  };
  return colors[status] || "FF000000";
}
